default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: TCC_VidaSaudavel_development

test:
  <<: *default
  database: TCC_VidaSaudavel_test

production:
  <<: *default
  database: TCC_VidaSaudavel_production
  username: TCC_VidaSaudavel
  password: <%= ENV['TCC_VIDASAUDAVEL_DATABASE_PASSWORD'] %>
