# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 791f27819c424e1e0ad2d8ded75a9d7e0a05291c78dbaeee8a504a042f4ff22eee10397ca58cd45939407ed5a13985fed5c080714fa258dfbd4702917035a21b

test:
  secret_key_base: e1ef0c74a1d527dc2da8555ad72938a98916cd13b4c452f21d57f70fe35af13733d16aaf5866aeb52f1ae4e7b9cce59d81f4893efdf7cf56b1dbd2fda9bf4155

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
